# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df7ac258715082e73bfb37220a2de913d6e7c1df1dfa3df3f04df195f7cc61d3725a9835d77a9e477434344324aaf8cccc93533934a68dd82678fd9300b98f1e

test:
  secret_key_base: 2444b1b4d5602f50cd1c987a5afe83f0073f8a4dd9cd783ec2e1503129aed8de390ee330ba52eaa9b19fafbf37e8128cde3389c6d0944d7864b97dae150c4446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
